---
# tasks file for elasticsearch
- name: Install elasticsearch required packages
  ansible.builtin.include_tasks: elastic_package.yml

- name: Install elasticsearch
  ansible.builtin.include_tasks: elasticsearch_install.yml
