---
# vars file for elasticsearch
elasticsearch_elastic:
  rpm_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  version: 7.15.2-x86_64
  repo: https://artifacts.elastic.co/packages/7.x/apt
  baseurl: https://artifacts.elastic.co/packages/8.x/yum
  network:
    host: 127.0.0.1
  http:
    port: 9200
